FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY . .

RUN go build -o calc-service ./cmd/calc_service/main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/calc-service /app/calc-service

EXPOSE 8080

CMD ["/app/calc-service"]