# Generated by Django 6.0.3 on 2026-03-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Black", "Black"),
                        ],
                        default="Silver",
                        max_length=10,
                    ),
                ),
                ("dealer_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KSO", "KSO"),
                            ("MANAGER", "Manager"),
                            ("ROP", "ROP"),
                            ("DIRECTOR", "Director"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("total_score", models.IntegerField(default=0)),
                ("volume_score", models.IntegerField(default=0)),
                ("deals_score", models.IntegerField(default=0)),
                ("bank_share_score", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.usermodels",
                    ),
                ),
            ],
        ),
    ]
