# Generated by Django 6.0.3 on 2026-03-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_userperformance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="ФИО сотрудника"),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                (
                    "deals_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество сделок (факт)"
                    ),
                ),
                (
                    "deals_plan",
                    models.IntegerField(
                        default=10, verbose_name="Количество сделок (план)"
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        default=0, verbose_name="Объём сделок, млн ₽ (факт)"
                    ),
                ),
                (
                    "volume_plan",
                    models.FloatField(
                        default=10, verbose_name="Объём сделок, млн ₽ (план)"
                    ),
                ),
                (
                    "bank_share",
                    models.FloatField(default=0, verbose_name="Доля банка, % (факт)"),
                ),
                (
                    "bank_share_goal",
                    models.FloatField(default=50, verbose_name="Целевая доля банка, %"),
                ),
                (
                    "approved_requests",
                    models.IntegerField(default=0, verbose_name="Одобренные заявки"),
                ),
                (
                    "submitted_requests",
                    models.IntegerField(default=0, verbose_name="Поданные заявки"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Black", "Black"),
                        ],
                        default="Silver",
                        max_length=20,
                        verbose_name="Уровень сотрудника",
                    ),
                ),
                (
                    "points",
                    models.FloatField(default=0, verbose_name="Баллы сотрудника"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.usermodels",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserPerformance",
        ),
    ]
