# Generated by Django 6.0.3 on 2026-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_employee_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Black", "Black"),
                        ],
                        default="Silver",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("income_growth_year", models.FloatField(default=0.0)),
                ("mortgage_saving_year", models.FloatField(default=0.0)),
                ("other_benefit_year", models.FloatField(default=0.0)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RatingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("gold_from", models.FloatField(default=70.0)),
                ("black_from", models.FloatField(default=90.0)),
                ("max_index", models.FloatField(default=120.0)),
                ("weight_volume", models.FloatField(default=0.35)),
                ("weight_deals", models.FloatField(default=0.25)),
                ("weight_bank_share", models.FloatField(default=0.25)),
                ("weight_conversion", models.FloatField(default=0.15)),
                ("silver_bonus", models.FloatField(default=0.0)),
                ("gold_bonus", models.FloatField(default=20000.0)),
                ("black_bonus", models.FloatField(default=40000.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
