# Generated by Django 6.0.3 on 2026-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_levelbenefit_ratingconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelbenefit",
            options={
                "verbose_name": "Льгота уровня",
                "verbose_name_plural": "Льготы уровней",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingconfig",
            options={
                "verbose_name": "Конфигурация рейтинга",
                "verbose_name_plural": "Конфигурации рейтинга",
            },
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="income_growth_year",
            field=models.FloatField(
                default=0.0, verbose_name="Рост дохода за год (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="level",
            field=models.CharField(
                choices=[("Silver", "Silver"), ("Gold", "Gold"), ("Black", "Black")],
                default="Silver",
                max_length=20,
                unique=True,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="mortgage_saving_year",
            field=models.FloatField(
                default=0.0, verbose_name="Экономия на ипотеке за год (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="other_benefit_year",
            field=models.FloatField(
                default=0.0, verbose_name="Прочие выгоды за год (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="black_bonus",
            field=models.FloatField(
                default=40000.0, verbose_name="Бонус уровня Black (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="black_from",
            field=models.FloatField(
                default=90.0, verbose_name="Порог уровня Black (балл)"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="gold_bonus",
            field=models.FloatField(
                default=20000.0, verbose_name="Бонус уровня Gold (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="gold_from",
            field=models.FloatField(
                default=70.0, verbose_name="Порог уровня Gold (балл)"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="max_index",
            field=models.FloatField(
                default=120.0, verbose_name="Максимальный индекс рейтинга"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название конфигурации"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="silver_bonus",
            field=models.FloatField(
                default=0.0, verbose_name="Бонус уровня Silver (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="weight_bank_share",
            field=models.FloatField(
                default=0.25, verbose_name="Вес показателя доли банка"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="weight_conversion",
            field=models.FloatField(
                default=0.15, verbose_name="Вес показателя конверсии"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="weight_deals",
            field=models.FloatField(
                default=0.25, verbose_name="Вес показателя количества сделок"
            ),
        ),
        migrations.AlterField(
            model_name="ratingconfig",
            name="weight_volume",
            field=models.FloatField(
                default=0.35, verbose_name="Вес показателя объёма продаж"
            ),
        ),
    ]
