# Generated by Django 6.0.3 on 2026-03-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_levelbenefit_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelPrivilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Название привилегии"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "financial_effect_rub",
                    models.FloatField(
                        default=0.0, verbose_name="Финансовый эффект (руб.)"
                    ),
                ),
                (
                    "unlock_level",
                    models.CharField(
                        choices=[
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Black", "Black"),
                        ],
                        default="Silver",
                        max_length=20,
                        verbose_name="Уровень разблокировки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Привилегия уровня",
                "verbose_name_plural": "Привилегии уровней",
                "ordering": ["title"],
            },
        ),
    ]
