# Generated by Django 6.0.3 on 2026-03-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_levelprivilege"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDailyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "deals_count",
                    models.IntegerField(default=0, verbose_name="Количество сделок"),
                ),
                (
                    "credit_volume",
                    models.FloatField(
                        default=0.0, verbose_name="Объём кредитов (руб.)"
                    ),
                ),
                (
                    "extra_products_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество дополнительных продуктов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневный результат сотрудника",
                "verbose_name_plural": "Ежедневные результаты сотрудников",
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
