# Generated by Django 6.0.3 on 2026-03-21 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_employeedailyresult"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="deals_plan",
            new_name="dels_plan",
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Создано",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="dealer_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="dealer_code"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="Email"),
        ),
    ]
