# Generated by Django 6.0.3 on 2026-03-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_rename_deals_plan_employee_dels_plan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="dels_plan",
            new_name="deals_plan",
        ),
    ]
