# Generated by Django 6.0.3 on 2026-03-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_rename_dels_plan_employee_deals_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelbenefit",
            name="bonus_income_year",
            field=models.FloatField(
                default=0.0, verbose_name="Годовой доход от бонусов (руб.)"
            ),
        ),
        migrations.AddField(
            model_name="levelbenefit",
            name="cashback_year",
            field=models.FloatField(default=0.0, verbose_name="Годовой кэшбэк (руб.)"),
        ),
        migrations.AddField(
            model_name="levelbenefit",
            name="dms_cost_year",
            field=models.FloatField(
                default=0.0, verbose_name="Годовые затраты на ДМС (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="levelbenefit",
            name="mortgage_saving_year",
            field=models.FloatField(
                default=0.0, verbose_name="Годовая экономия по ипотеке (руб.)"
            ),
        ),
    ]
