# Generated by Django 6.0.3 on 2026-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_levelbenefit_bonus_income_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("deals", "Deals"),
                            ("volume", "Volume"),
                            ("bank_share", "Bank Share"),
                            ("extra_products", "Extra Products"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_value", models.FloatField()),
                ("reward_points", models.FloatField()),
                ("deadline", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
