# Generated by Django 6.0.2 on 2026-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Свободных мест"),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время ивента")),
            ],
        ),
    ]
